<a href="https://colab.research.google.com/github/AshOne91/PLAYDATA-COLAB/blob/main/3_%EB%AC%B8%EC%9E%90%EC%97%B4%EA%B3%BC_%EC%9E%85%EC%B6%9C%EB%A0%A5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 실습1


In [ ]:
# 문장을 입력받아서  1.소문자로 변환, 2. 공백을 제거
# 자연어처리에서 대소문자 구분, 불필요한 공백을 제거
text = input("문장을 입력하세요 ")
# 소문자로 변환
text_lower = text.lower()
# 공백제거
text_strip = text.strip()
print(f'소문자로 변환 : {text_lower}')
print(f'공백제거 : {text_strip}')

In [ ]:
# 자연어처리에서 단어를 토큰으로 분리하는 기초작업
# 문자열 분리, 문자열을 입력받아서 다양하게 분리... 기본이 공백, 분리된 토큰의 개수
text = input("문장을 입력하세요 ")
words = text.split()
print(f'분리된 단어리스트 {words}')
print(f'단어개수 {len(words)}')

In [ ]:
# 차수 - 차원 개념
x1 = [1,2,3,4]  # 1 차원 데이터  벡터           x1[2]
x2 = [x1,x1,x1,x1] #  2 차원 데이터    행렬
x3 = [x2,x2,x2,x2]

import numpy as np  # array  배열
x2_numpy = np.array(x2)
print(x2_numpy)
print(x2_numpy[:,1:3])

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
[[2 3]
 [2 3]
 [2 3]
 [2 3]]


In [ ]:
# 문자열 결합 : 전처리된 단어들을 결합하거나. 새로운 문자열을 만드는 연습 - 데이터 가공
# 3개의 단어를 공백으로 분리해서 입력   apple, banana, grap
# 분리된 단어를 각각의 변수에 저장하거나 또는 리스트변수에 저장
# 각 단어에서 a 문자를 제거하고
# 단어를 공백을 기준으로 합치기
words = input("3개의 단어를 입력하세요 ").split()
words[0] = words[0].replace('a','')
words[1] = words[1].replace('a','')
words[2] = words[2].replace('a','')
words = ' '.join(words)
print(words)

3개의 단어를 입력하세요apple banana grap
pple bnn grp


In [ ]:
# 자연어 처리에서 특정 패턴(접두사, 접미사)을 추출하거나 분석할때
# 문자열에서 특정 부분 추출  slicing
#1.  사용자로부터 문자열을 입력받아서
#2.  처음 5글자 출력    # 문자열의 길이가 5 이상일때만
#3.  마지막 3글자 출력
text = input("문자열을 입력하세요 ")
if len(text) >= 5:
  print(f'처음 5글자 : {text[ : 5]}')
  print(f'마지막 3글자 : {text[ -3 : ]}')
else:
  print('5 글자가 넘어야 합니다.')

문자열을 입력하세요 즐거운 금요일
처음 5글자 : 즐거운 금
마지막 3글자 : 금요일


In [ ]:
# 파일에서 확장자가 txt이며 "텍스트 파일" 출력  단일 조건
# 확장자가 .mp4 , avi, mpeg 이면 "동영상 파일"  다중 조건
# 확장자가 .ini 이면 "설정 파일"  이라고 출력   단일 조건

import random
files = ['text.txt','video.part1.avi','movie.mpeg','config.ini', 'document.doc']
# 이중에 임의의 데이터 하나를 선택해서   random.choice()  함수 이용
selecte_file = random.choice(files)
print(f'선택된 파일 : {selecte_file}')
extention_file = selecte_file.split('.')[-1]  # ***
if extention_file == 'txt':
  print('텍스트 파일')
elif extention_file == 'avi' or extention_file == 'mpeg' or extention_file == 'mp4':
  print('동영상 파일')
elif extention_file == 'ini':
  print('설정 파일')
else:
  print('처리할 수 없는 파일 입니다.')

선택된 파일 : document.doc
처리할 수 없는 파일 입니다.


In [ ]:
# 자연어 처리 : 텍스트 정규화과정에서 대소문자 체크 변환
# 문장을 입력받아서(영어)
# 대문자가 포함되어 있으면 소문자로 변환  # 무조건 소문로 변환 x
# 정규식을 이용

In [ ]:
# 대문자가 포함여부  ??? 무조건 소문자로 변환
text = "Hello World"
if text != text.lower():
  text = text.lower()

print(text)

hello world


In [ ]:
# 정규식... 문자열에서 패턴을 검색  regular expresion
import re
# text = "Hello World"
text = input("영어 문자열 입력 ")
isUpper = bool(re.search(r'[A-Z]',text))   # [ ] 대괄호 안에 문자를 넣으면 해당 문자들 중 하나라도 존재하면 매칭(True)
if isUpper:
  print(text.lower())
else:
  print("입력하신 문자열은 전부 소문자 입니다. ")


영어 문자열 입력 hello world  gooD
hello world  good


In [ ]:
# 자연어 처리 : 키워드 검색기능 .. 문자열 내에서 특정 패턴을 검사
# 입력한 문자열에서 특정 단어의 포함 여부 확인
# i love programming and i like python  'like' 포함여부
text = input("문장을 입력하세요")
find_word = 'like'
if find_word in text:
  print("like 단어가 포함되어 있습니다.")
else:
  print("like 단어가 없습니다.")

문장을 입력하세요i love programming and i like python 
like 단어가 포함되어 있습니다.


In [ ]:
# 자연어 처리.....  구두점을 체크... (제거)
# . , !  --> 포함여부를 확인하고.. 해당 문자열에서 제거
text = input("intput sentece ")
if '.' in text or ',' in text or '!' in text:
  print('구두점 포함되어 있습니다.')
  text = text.replace('.','').replace(',','').replace('!','')
else:
  print('구두점 이 없습니다.')

In [ ]:
# 텍스트에서 불필요한 공백을 제거해서 데이터를 깔끔하게 처리
# 연속된 공백을 하나의 공백으로 정리
# 조건문을 이용... 연속된공백을찾아서... 공백을 하나로 만듦
# i   like python  -> i like python
text = 'i   like python'
if "  " in text:
  print(' '.join(text.split()) )

i like python


# 순환문
  - for  / while

In [ ]:
for i in range(3):
  print(f"안녕하세요 {i}")

안녕하세요 0
안녕하세요 1
안녕하세요 2


In [ ]:
import random
samples = random.sample(range(1,46),6)
print(samples)
for i in samples:
  # 리스트의 짝수만 추출
  if i % 2 == 0:
    print(i)

[38, 20, 15, 25, 2, 10]
38
20
2
10


In [ ]:
# 단순히 어떤로직을 특정 횟수만큼 반복
# for i in range(5):  # i의 사용용도가 없다면 혹시나 내부에서 i변수가 잘못 사용될수 있으니
#   print("검사")

for _ in range(5):
  print("검사")

검사
검사
검사
검사
검사


In [ ]:
def myFunc():
  return 0.85, 0

a, _ = myFunc()
print(a)

0.85


while

In [ ]:
count = 5
while count > 0:
  print("좋아용")
  count -= 1

좋아용
좋아용
좋아용
좋아용
좋아용


In [ ]:
# 임의자연수 (0 ~ 29) 5 추출해서 그 합이 100을넘으면 종료하고 그때의 랜덤리스트를 출력
import random  # 모듈 불러오기

random_lists = random.sample(range(30),5)  # 임의 자연수 집합 생성
total = sum(random_lists)  # 자연수집합들의 합  total : 90

count = 0  # 변수 초기화
while total <= 100:  # 순환문의 진입  조건
  count += 1
  random_lists = random.sample(range(30),5)
  total = sum(random_lists)

print(random_lists, total, count)



[14, 27, 23, 24, 22] 110 37


break

In [ ]:
# 임의자연수 (0 ~ 29) 5 추출해서 그 합이 100을넘으면 종료하고 그때의 랜덤리스트를 출력
import random


while True:

  random_lists = random.sample(range(30),5)
  total = sum(random_lists)
  if total > 100:
    break

print(random_lists, total)


[22, 21, 13, 29, 27] 112


continue

In [ ]:
# 짝수만 추출해서 리스트에 담기
result = []
for i in random.sample(range(100), 15):
  if i % 2 != 0:  #홀수일대만 skip
    continue
  result.append(i)  # 짝수만 저장

result

[24, 60, 52, 14, 4, 34, 82, 78]

In [ ]:
# 자연어 처리.....  구두점을 체크... (제거)
# . , !  --> 포함여부를 확인하고.. 해당 문자열에서 제거
# text = input("intput sentece ")
# if '.' in text or ',' in text or '!' in text:
#   print('구두점 포함되어 있습니다.')
#   text = text.replace('.','').replace(',','').replace('!','')
# else:
#   print('구두점 이 없습니다.')

  # 순환문을 이용한 방법으로 개선  구두점 리스트로 만들어
  # 리스트의 있는 요소가 문장에 포함되어 있는지 검사   -순환문을 이용해서
  # 있으면 해당 구두점을 제거하는 replace를 실행
text = input("intput sentece ")
remove_lists = ['.', ',', '!', '@']
for char in remove_lists:
  if char in text:
    text = text.replace(char, '')

print(f'구두점 제거 : {text}')

intput sentece 즐거운! 금요일. 입@@@니다
구두점 포함되어 있습니다.
구두점 포함되어 있습니다.
구두점 포함되어 있습니다.
구두점 제거 : 즐거운 금요일 입니다


In [ ]:
# 구구단 출력
for i in range(1, 10): # 1 ~9
  print(f'2 x {i} = {2*i}')

2 x 1 = 2
2 x 2 = 4
2 x 3 = 6
2 x 4 = 8
2 x 5 = 10
2 x 6 = 12
2 x 7 = 14
2 x 8 = 16
2 x 9 = 18


In [ ]:
# 중첩 for   print()
for i in range(2,10):
  for j in range(1,10):
   print(f'{i} x {j} = {i*j}', end='\t')
  print()


2 x 1 = 2	2 x 2 = 4	2 x 3 = 6	2 x 4 = 8	2 x 5 = 10	2 x 6 = 12	2 x 7 = 14	2 x 8 = 16	2 x 9 = 18	
3 x 1 = 3	3 x 2 = 6	3 x 3 = 9	3 x 4 = 12	3 x 5 = 15	3 x 6 = 18	3 x 7 = 21	3 x 8 = 24	3 x 9 = 27	
4 x 1 = 4	4 x 2 = 8	4 x 3 = 12	4 x 4 = 16	4 x 5 = 20	4 x 6 = 24	4 x 7 = 28	4 x 8 = 32	4 x 9 = 36	
5 x 1 = 5	5 x 2 = 10	5 x 3 = 15	5 x 4 = 20	5 x 5 = 25	5 x 6 = 30	5 x 7 = 35	5 x 8 = 40	5 x 9 = 45	
6 x 1 = 6	6 x 2 = 12	6 x 3 = 18	6 x 4 = 24	6 x 5 = 30	6 x 6 = 36	6 x 7 = 42	6 x 8 = 48	6 x 9 = 54	
7 x 1 = 7	7 x 2 = 14	7 x 3 = 21	7 x 4 = 28	7 x 5 = 35	7 x 6 = 42	7 x 7 = 49	7 x 8 = 56	7 x 9 = 63	
8 x 1 = 8	8 x 2 = 16	8 x 3 = 24	8 x 4 = 32	8 x 5 = 40	8 x 6 = 48	8 x 7 = 56	8 x 8 = 64	8 x 9 = 72	
9 x 1 = 9	9 x 2 = 18	9 x 3 = 27	9 x 4 = 36	9 x 5 = 45	9 x 6 = 54	9 x 7 = 63	9 x 8 = 72	9 x 9 = 81	


In [ ]:
# 중첩 for   print()
for i in range(1,10):
  for j in range(2,10):
   print(f'{j} x {i} = {i*j}', end='\t')
  print()

2 x 1 = 2	3 x 1 = 3	4 x 1 = 4	5 x 1 = 5	6 x 1 = 6	7 x 1 = 7	8 x 1 = 8	9 x 1 = 9	
2 x 2 = 4	3 x 2 = 6	4 x 2 = 8	5 x 2 = 10	6 x 2 = 12	7 x 2 = 14	8 x 2 = 16	9 x 2 = 18	
2 x 3 = 6	3 x 3 = 9	4 x 3 = 12	5 x 3 = 15	6 x 3 = 18	7 x 3 = 21	8 x 3 = 24	9 x 3 = 27	
2 x 4 = 8	3 x 4 = 12	4 x 4 = 16	5 x 4 = 20	6 x 4 = 24	7 x 4 = 28	8 x 4 = 32	9 x 4 = 36	
2 x 5 = 10	3 x 5 = 15	4 x 5 = 20	5 x 5 = 25	6 x 5 = 30	7 x 5 = 35	8 x 5 = 40	9 x 5 = 45	
2 x 6 = 12	3 x 6 = 18	4 x 6 = 24	5 x 6 = 30	6 x 6 = 36	7 x 6 = 42	8 x 6 = 48	9 x 6 = 54	
2 x 7 = 14	3 x 7 = 21	4 x 7 = 28	5 x 7 = 35	6 x 7 = 42	7 x 7 = 49	8 x 7 = 56	9 x 7 = 63	
2 x 8 = 16	3 x 8 = 24	4 x 8 = 32	5 x 8 = 40	6 x 8 = 48	7 x 8 = 56	8 x 8 = 64	9 x 8 = 72	
2 x 9 = 18	3 x 9 = 27	4 x 9 = 36	5 x 9 = 45	6 x 9 = 54	7 x 9 = 63	8 x 9 = 72	9 x 9 = 81	


In [ ]:
random.sample(range(10),5)
list_2 = []
for i in range(3):
  list_2.append(random.sample(range(10),5))

# 시각적인 확인용
for row in list_2:
  print(row)


for i in range(len(list_2)):
  print(f'list_2의 {i}번째 가로의 합 : {sum(list_2[i])}')

for i in range(len(list_2[0])):  # 0 ~ 4
  temp = 0
  for j in range(len(list_2)):
    temp += list_2[j][i]
  print(f'list_2의 {i}번째 세로의 합 : {temp}')

[6, 0, 4, 9, 2]
[8, 2, 4, 3, 6]
[9, 0, 1, 6, 3]
list_2의 0번째 가로의 합 : 21
list_2의 1번째 가로의 합 : 23
list_2의 2번째 가로의 합 : 19
list_2의 0번째 세로의 합 : 23
list_2의 1번째 세로의 합 : 2
list_2의 2번째 세로의 합 : 9
list_2의 3번째 세로의 합 : 18
list_2의 4번째 세로의 합 : 11


In [ ]:
list_1 = [1,5,7]
list_2= [ list_1,list_1  ]
print(f'list_2 는 2차원 리스트')  # 행렬
# row(행,가로,데이터) , col(열,세로,특성)
# row : 2  col: 3  (2,3)
# 행의개수  2차원의 데이터 개수  len(list_2)
# 열의개수 len(list_2[0])
# 2차원 데이터의 모든 데이터를 순환하려면
for i in range(len(list_2)):
  for j in range(len(list_2[0])):
    print(f'list_2[{i}][{j}] = {list_2[i][j]}')

list_2 는 2차원 리스트
list_2[0][0] = 1
list_2[0][1] = 5
list_2[0][2] = 7
list_2[1][0] = 1
list_2[1][1] = 5
list_2[1][2] = 7


In [ ]:
fruits = ['사과','배','바나나','포도','사과','딸기','사과']
# 사과의 개수를 구하세요  for문을 이용해서
count = 0
for fruit in fruits:
  if fruit == '사과':
    count += 1
print(f'사과의 개수 : {count}')

사과의 개수 : 3


In [ ]:
while True:
  isContinue = input('계속하시겠습니까 (y/Y) ')
  if isContinue.loweraa() == 'y':
    break

계속하시겠습니까 (y/Y) a
계속하시겠습니까 (y/Y) 
계속하시겠습니까 (y/Y) 
계속하시겠습니까 (y/Y) Y


In [ ]:
# while 문
# 1. 나이를 입력받는다
# 2, 나이에 따른 입장료를 계산  (성인 청소년 어린이)
# 3. 입장료를 수입(total)에 누적
# 4. 계속할지 물어본다 - break


# 5. 프로그램 이 종료가 되면
# 6 총 수입금액을 출력(total)


In [ ]:
total = 0  # 총 수입을 저장할 변수

while True:
    # 나이를 입력받는다
    age = int(input("나이를 입력하세요: "))

    # 나이에 따른 입장료 계산
    if age >= 19:  # 19 20 21
        entrance_fee = 10000  # 성인
    elif age >= 13:  # 13 ~ 18
        entrance_fee = 7000  # 청소년
    elif age >= 8:
        entrance_fee = 3000  # 어린이
    else:
        print('잘못된 나이 (8살 이상 입력)')
        continue  # 잘못된 나이는 다시 입력받기

    # 입장료를 수입에 누적
    total += entrance_fee

    # 계속할지 물어본다
    continue_program = input("계속하시겠습니까? (y/Y): ")
    if continue_program.lower() != 'y':
        break

# 프로그램 종료 후 총 수입금액 출력
print(f"총 수입금액은 {total:,}원입니다.")


나이를 입력하세요: 25
계속하시겠습니까? (y/Y): y
나이를 입력하세요: 12
계속하시겠습니까? (y/Y): y
나이를 입력하세요: 4
잘못된 나이 (8살 이상 입력)
나이를 입력하세요: 80
계속하시겠습니까? (y/Y): 13
총 수입금액은 23000원입니다.


In [ ]:
total = 25000
print(f"총 수입금액은 {total:,}원입니다.")  # 쉼표 추가하여 출력

총 수입금액은 25,000원입니다.


In [ ]:
# 천단위로 , 표시하기
price = 25000
price = str(price)
count = 0
result = []
for c in price[::-1]:
  count += 1
  result.append(c)
  if count % 2 == 0:
    result.append(',')
if result[-1] == ',':
  result.pop()  # 리스트의 가자 마지막을 리스트에서 제거하고 제거된 값을 리턴

result = ''.join(result[::-1])
print(result)

2,50,00


In [ ]:
# 영어에서 모음  aeiouAEIOU
# 문자열에서 모음개수를 세어보기
# Hello Python
# for, if, in --> 포함여주 알려주는
# count

text = "Hello machine learning"  # 3개
value = "aeiouAEIOU"

count = 0
for c in text:
  if c in value:
    count += 1

print(f'모음의 개수는 : {count}')

모음의 개수는 : 8


In [ ]:
import string
print(string.punctuation)
# 문장에서 특수기호에 해당하는 단어를 삭제
text = '''
에코프로비엠이 코스피시장 이전 상장을 철회하면서 주가가 급락하고 있다.에코프로비엠 주식은 28일 오전 11시 15분 코스닷시장에서 12만100원에 거래됐다. 전날보다 주가가 10.37%(1만3900원) 내렸다.

에코프로비엠은 이날 오전 11시 코스피시장 이전상장을 철회한다고 공시했다. 지난해 11월 이전상장을 위한 예비심사신청서를 접수하고 3개월 만이다.

에코프로비엠은 “여러 제반 요건을 고려해 이전상장 신청의 건을 철회하기로 했다”며 “향후 경영실적 개선 확인 후 유가증권시장(코스피시장) 이전상장 예비심사를 재신청할 예정”이라고 밝혔다.

- Copyright ⓒ 조선비즈 & Chosun.com -

Copyright © 조선비즈. 무단전재 및 재배포 금지.'''

for c in string.punctuation:
  text = text.replace(c,'')

print(text)


!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~

에코프로비엠이 코스피시장 이전 상장을 철회하면서 주가가 급락하고 있다에코프로비엠 주식은 28일 오전 11시 15분 코스닷시장에서 12만100원에 거래됐다 전날보다 주가가 10371만3900원 내렸다

에코프로비엠은 이날 오전 11시 코스피시장 이전상장을 철회한다고 공시했다 지난해 11월 이전상장을 위한 예비심사신청서를 접수하고 3개월 만이다

에코프로비엠은 “여러 제반 요건을 고려해 이전상장 신청의 건을 철회하기로 했다”며 “향후 경영실적 개선 확인 후 유가증권시장코스피시장 이전상장 예비심사를 재신청할 예정”이라고 밝혔다

 Copyright ⓒ 조선비즈  Chosuncom 

Copyright © 조선비즈 무단전재 및 재배포 금지


In [ ]:
# startwith  ~로 시작하는 문자열
# endwith  ~로 끝나는 문자열
text = 'python is easy'
text.endswith("easy")
text = '집은 좋다 공부는 어렵다 학교는 재미있다 우리는 즐겁다'
# '는'으로 끝나는 단어를 찾아서출력  공부는, 학교는, 우리는       endwith('는')
for w in text.split():
  if w.endswith('는'):
    print(w)

공부는
학교는
우리는


In [ ]:
# 문장에서 긍정적인 단어 감지
sentences = [
    '영화가 재미있어요',
    '날씨가 좋아요',
    '음식이 별로에요',
    '이 책을 추천 합니다.'
]
positive_lists = ['재미있어요','좋아요','추천']
# 해당문장에서 긍정적인 문장을 출력
for sentence in sentences:          # sentece  -> 영화가 재미있어요
  for check in positive_lists:      # check -> 재미있어요
    if check in sentence:           # 재미있어요 in  영화가 재미있어요
      print(f'긍정적인 문장 : {sentence}')

긍정적인 문장 : 영화가 재미있어요
긍정적인 문장 : 날씨가 좋아요
긍정적인 문장 : 이 책을 추천 합니다.


In [ ]:
# 주어진 문장에서 모든 대문자 단어를 추출
# for  isupper()  모든 대문자를 출력
text = 'I love NLP and Python is FUN'
# I NLP FUN
upper_lists = []
for w in text.split():
  if w.isupper():
    upper_lists.append(w)
print(upper_lists)

['I', 'NLP', 'FUN']


In [ ]:
# 주어진 문장에서 공백을 기준으로 단어를 분리한다음
# 단어의 길이가 2개 이하인 단어들만 리스트에 담아서 출력
text = '''
대한축구협회는 28일 보도자료를 통해 '2031년 아시아축구연맹(AFC) 아시안컵 개최에 대한 유치 의향서(Expression of interst to host)를 지난 27일 AFC에 제출했다'고 밝혔다.
'''

under_2_word = []
for word in text.split():
  if len(word) <= 2:
    under_2_word.append(word)

print(under_2_word)

['통해', '대한', '유치', 'of', 'to', '지난']


In [ ]:
# 텍스트에 연속된 단어쌍을 만들기
text = "나는 수업이 끝나고 집에 가서 열심히 공부한다"
# n-gram 기법   n = 2
# '나는  수업이', '수업이 끝나고', '끝나고 집에', '집에 가서', '가서 열심히', '열심히 공부한다'
text = text.split()
print(text)
for i in range(len(text)-1):
  print(text[i]+' ' + text[i+1])

['나는', '수업이', '끝나고', '집에', '가서', '열심히', '공부한다']
나는 수업이
수업이 끝나고
끝나고 집에
집에 가서
가서 열심히
열심히 공부한다


In [ ]:
# 사용자로부터 단어를입력받어서 문장을 만들어 나가기
start ='옛날옛적에'


# 사용자 입력 : 호랑이가
# 출력 : 옛날옛적에 호랑이가

# 사용자 입력 : 떡하나주면
# 출력 : 옛날옛적에 호랑이가 떡하나주면

# 사용자 입력 : 안잡아먹지
# 출력 : 옛날옛적에 호랑이가 떡하나주면 안잡아먹지

# 사용자 입력 : 끝

# while, 문장을 저장할 리스트,  리스트의 문장을 하나로 합칠 join, 사용자 입력을 받아드릴 input
# break : 끝  이 입력되면 순환문 탈출
text = ''
while True:
  print(f'현재 문장 : {start}')
  text = input('다음단어 입력 : ')
  if text == '끝':
    break
  start +=  f' {text}'

print(f'최종문장 : {start}')

현재 문장 : 옛날옛적에
다음단어 입력 : 호랑이
현재 문장 : 옛날옛적에 호랑이
다음단어 입력 : 담배피던
현재 문장 : 옛날옛적에 호랑이 담배피던
다음단어 입력 : 끝
최종문장 : 옛날옛적에 호랑이 담배피던


In [ ]:
# 여러문장이 있을때 문장별로 토큰화
text = '나는 학교에 간다. 친구를 만난다. 집에 온다'
# expect : ['나는 학교에간다', '친구를 만난다', '집에 온다']
result = []
for sentece in text.split('.'):
  result.append(sentece.strip())

print(result)

['나는 학교에 간다', '친구를 만난다', '집에 온다']


- 기사내용을 스크랩하고
- 형태소 분석기를 도입해서 한글의 명사를 추출한후
- 명사의 개수를 카운트해서 빈도수가 높은 단어 상위 10개만 추출해 보기
- dictionary라는 자료구조를 사용할수 도 있지만.. -- 배운후에 사용해 보기

In [ ]:
!pip install konlpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.4/19.4 MB 63.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 494.1/494.1 kB 27.3 MB/s eta 0:00:00


형태소 : ['인공', '지능', '은', '앞', '으로', '보편화', '될거', '같습니다', '.']


In [ ]:
# 형태소 분석기( 명사 형용사 부사)
from konlpy.tag import Okt
# Okt 클래스의 객체 생성
okt = Okt()  # Okt 클래스... okt 객체변수

text = '인공지능은 앞으로 보편화 될거 같습니다.'
morphs = okt.morphs(text)
print(f"형태소 : {morphs}")

pos = okt.pos(text)
print(f"품사태깅 : {pos}")
nouns = okt.nouns(text)
print(f"명사 : {nouns}")

형태소 : ['인공', '지능', '은', '앞', '으로', '보편화', '될거', '같습니다', '.']
품사태깅 : [('인공', 'Noun'), ('지능', 'Noun'), ('은', 'Josa'), ('앞', 'Noun'), ('으로', 'Josa'), ('보편화', 'Noun'), ('될거', 'Verb'), ('같습니다', 'Adjective'), ('.', 'Punctuation')]
명사 : ['인공', '지능', '앞', '보편화']


In [ ]:
!pip install konlpy
from konlpy.tag import Okt
# text = ''
# 인터넷 뉴스기사를 스크랩해서 파일에 저장한다음
# text 에는 파일에서 읽어서 저장하고
with open('/content/drive/MyDrive/data/kor_news.txt', 'r',encoding='utf8') as f:
  text = f.read()
nouns = okt.nouns(text)
print(nouns[:10])
# nouns 명사들의 리스트 집합
# 추출된 명사의 길이가 2글자 이상인 것만 다시 추려서
selected_nouns = []
for word in nouns:
  if len(word) > 2:
    selected_nouns.append(word)
print(selected_nouns[:10])
# from collection import Counter 를 이용해서
from collections import Counter
# 각 단어의 빈도수를 구해서
count = Counter(selected_nouns)
# mostcommon(10)  상위 10개의 단어만 추출해 보자
print(count.most_common(10))
# 리스트안에 튜플형식으로 구성되어 있는데. 여기서 튜플에서 텍스트만 추출해서 출력
for word, _ in count.most_common(10):
  print(word)

['디지털', '데일', '리가', '퇴근', '즈음', '수', '퇴근길', '코너', '마련', '하루']
['디지털', '퇴근길', '퇴근길', '디지털', '기지국', '기지국', '생태계', '이동통신', '가운데', '서비스']
[('데이터', 12), ('반도체', 10), ('개정안', 7), ('카카오', 6), ('모빌리티', 6), ('클러스터', 6), ('연구개발', 5), ('기지국', 3), ('생태계', 3), ('서비스', 3)]
데이터
반도체
개정안
카카오
모빌리티
클러스터
연구개발
기지국
생태계
서비스
